version: 0.0
os: linux

files:
  - source: .
    destination: /home/ubuntu/deploy/be

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 60
      runas: root
      
  AfterInstall:
    - location: scripts/fetch-env-from-ssm.sh
      timeout: 120
      runas: root
      
    - location: scripts/deploy.sh
      timeout: 300
      runas: root
      
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 120
      runas: root
      
  ValidateService:
    - location: scripts/healthcheck.sh
      timeout: 150
      runas: root